#!/usr/bin/env bash
#comment
i=1
while [ $i -le 20 )
do
  case $i in
 4)
   echo -e "$i\nbad luck from China"
   ;;

 9)
   echo -e "$i\nbad luck from Japan"
   ;;

 17)
   echo -e "$i\nbad luck from Italy"
   ;;

 *) 
  case$i
  esac
  ((i++))
done

