#!/usr/bin/env bash
#To file, or not to file
filename="school"
if [ -e "$filename"];then
	echo "school file exists"
	if [-s "$filename"] ;then
		echo "school file is not empty"
	else
		echo "school is empty"
	fi
	if [-f "$filename"] ;then
		echo "school is regular file"
	fi
else
	echo "school file does not exist"
fi

