#!/usr/bin/env bash
#To file, or not to file
filename="school"
if [ -e "$filename" ]; then
 echo "schoolfile exists"
else
 echo "schoolfile does not exist"
fi
if [ -s "$filename" ]; then
 echo "school file is empty"
else
 echo "school file is not empty"
fi
if [ -f "$filename" ]; then
 echo "school is a regular file"
fi
