#!/usr/bin/env bash
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
echo $$ > "/var/run/myscript.pid"
while :
do
  trap echo "Y U no love me?!" SIGINT
  trap echo "I hate the kill command" && rm /var/run/myscript.pid SIGTERM
  trap echo "rm /var/run/myscript.pid" SIGQUIT
done
