#!/usr/bin/env bash
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
echo $$ > "/var/run/myscript.pid"

  trap echo "I hate the kill command" SIGTERM
  trap echo "Y U no love me?!" SIGINT
  trap rm -f /var/run/myscript.pid; exit SIGQUIT

while :
do 
	echo "To infinity and beyond"
done
